### ISSUE TITLE
Feeds with duplicate items (matching IDs/URLs) create new entries on every fetch

### ISSUE THREAD

**Issue by mthamil** [brief-rss/brief#344]
I subscribe to the following feed: https://blogs.technet.microsoft.com/cloudplatform/rssfeeds/devblogs. 
Every week or so, there will be a few posts that keep coming back, many, many times. I repeatedly have to keep marking these items read since they fill up my feed list. I **do** have "Don't mark changed items back as unread" checked.

This week it's "ASP.NET Core 2.1.0-preview1: Functional testing of MVC applications", "Last week in Azure #21: Week of February 26", and "Microsoft releases automation for HIPAA/HITRUST compliance".

I understand that this is probably not Brief's fault, and it is likely due to something Microsoft is doing wrong with the feed. However, would there be any way to combat this? Maybe an option to check for the exact same title?

**Comment by tanriol** [comment]
Do they come back with the "updated" mark or without it? Could you please look at the entries and check whether these entries are in the list once or several times each?

**Comment by mthamil** [comment]
Every time they come back they create new entries. If I show all items instead of just unread, it's a huge number of dupes.

**Comment by tanriol** [comment]
I seem unable to reproduce this problem at the moment... are there, in your experience, problematic items in the feed at the moment?

**Comment by mthamil** [comment]
Not currently, it has stopped this week after a few days. It will likely happen against next week.

**Comment by mthamil** [comment]
Ok, it's happening with a Hanselman post right now.

**Comment by mthamil** [comment]
Now there are three more that are repeating.

**Comment by tanriol** [comment]
Hmm... ok, the problem is that the items are, quite literally, duplicated in the feed and thus have duplicate IDs and links, which causes Brief some problems when storing them. Something needs to be done.

**Comment by bdcomp** [comment]
I think I got this too, from this feed https://www.ebayinc.com/stories/news/rss/

**Comment by tanriol** [comment]
@bdcomp Not seeing this bug at your URL, at least right now with the development version.

**Comment by bdcomp** [comment]
It was with some earlier entries, about 2 weeks ago.
Now, seems OK.

**Comment by simonlindholm** [comment]
This just started happening for me with http://imrannazar.com/rss.xml and http://blog.cr.yp.to/feed.application=xml, FWIW (every new fetch adds another 100 identical items). The common theme seems to be that they use RSS 2.0 and lack `<guid>`s (maybe previous brief versions disambiguated by URL and now it doesn't?).

**Comment by tanriol** [comment]
@simonlindholm Could you please check your Brief version? This looks like a bug in Brief 2.5.6 and 2.5.7, but should be fixed in yesterday's 2.5.8 release.

**Comment by simonlindholm** [comment]
Ahh, I didn't see that there was a new release! Thanks, that fixes it. :)

**Comment by retedeh** [comment]
The bug still happens on 2.5.8. Feed items get duplicated every time the feed gets refreshed. https://postimg.cc/image/i20mlaxm3/

**Comment by mthamil** [comment]
Yeah, it still happens to me all the time with those Microsoft feeds I originally posted about.

**Comment by Cimbali** [comment]
I can reproduce this on the following youtube atom feed: https://www.youtube.com/feeds/videos.xml?playlist_id=PL0H7ONNEUnnt59niYAZ07dFTi99u2L2n_

Here's [a gist with just the 2 feed items that cause the issue](https://gist.github.com/Cimbali/547832e07afde1ba00d214aab9be9c91). You can subscribe to the "raw" gist-hosted file with brief-rss and see that every time you refresh there is a new item in the feed.

Duplicate items are invalid anyway so would it be acceptable to squash any number of items with matching id+date (or whatever you use to uniquely identify them) as just one?
See also:
https://validator.w3.org/feed/docs/warning/DuplicateEntries.html
https://validator.w3.org/feed/docs/warning/DuplicateUpdated.html
