### ISSUE TITLE
Sorting feeds no longer works

### ISSUE THREAD

**Issue by Wombat2018** [brief-rss/brief#517]
Hi,

with the current Firefox version (98.0), the feeds can no longer be sorted. I would be happy about an update.

**Comment by Ngamer01** [comment]
I can confirm this doesn't work on the ESR branch either (I'm using 91.7.0esr).  When I try to move a feed in Organize mode, the cursor turns into a stop sign signaling feed moving can't be done.  I'm on Windows 10, version 21H2.

![image](https://user-images.githubusercontent.com/13906808/157707055-7c03542a-0ca1-469a-be08-019e760dc7f8.png)

Even though the screenshot can't show my mouse cursor, normally when you move a feed, a line should appear where you want to move the feed to.  In this screenshot, you cannot see the lines in the feeds.  The lines only appear around folders.

**Comment by tanriol** [comment]
Thank you for the report, I'll try reproducing this in a few days.

**Comment by tanriol** [comment]
Broken after [this Firefox commit](https://hg.mozilla.org/integration/autoland/rev/a566c029f7a5af517126482475f022cb675dbd98). The corresponding bug is non-public (security). I've asked on Matrix whether this is an oversight that's to be fixed in Firefox or outdated information on MDN. Anyway, Brief needs some workaround for that.

**Comment by Wombat2018** [comment]
When can we expect an update which fixes this problem?

**Comment by tanriol** [comment]
I'll try to make one this week or early next week. Not sure about the addons.mozilla.org publishing delay.

**Comment by tanriol** [comment]
Fixed in 003e2877282ad18af6313570c233836e019d704d, now I just need to make a release with that.

**Comment by etienne1911** [comment]
was it released? still having issue on this version
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1556719/173375815-39348f2b-b9ae-4316-ac15-94b7be379b31.png">

**Comment by tanriol** [comment]
Not yet, I'll try to make a release in a few days as I've got a more serious problem on top of this one too.

**Comment by tanriol** [comment]
Fix released in 2.6.1.
